In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('assets/data/aug_train.csv')

## How Big is the data?

In [5]:
df.shape

(19158, 14)

## How does the data look like?

In [6]:
# the best unbiased way is to use sample instead of head
df.sample(5)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
15086,17087,city_73,0.754,Male,No relevent experience,Full time course,Graduate,STEM,2,NaN,NaN,1,35,1.0
19136,23672,city_21,0.624,NaN,Has relevent experience,no_enrollment,Masters,STEM,6,NaN,NaN,1,5,1.0
7958,27273,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,11,10000+,Pvt Ltd,1,104,0.0
190,26099,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,12,10000+,Pvt Ltd,1,60,0.0
3170,4433,city_160,0.920,Female,Has relevent experience,Full time course,Graduate,STEM,5,100-500,Pvt Ltd,2,23,0.0

## What is the data type of the COlumns?

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  str
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  str
 4   relevent_experience     19158 non-null  str
 5   enrolled_university     18772 non-null  str
 6   education_level         18698 non-null  str
 7   major_discipline        16345 non-null  str
 8   experience              19093 non-null  str
 9   company_size            13220 non-null  str
 10  company_type            13018 non-null  str
 11  last_new_job            18735 non-null  str
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), str(10)
memory usage: 2.0 MB

u can change the datatype of columns to save memory space

## Are there any missing values?

In [11]:
df.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    4508
relevent_experience          0
enrolled_university        386
education_level            460
major_discipline          2813
experience                  65
company_size              5938
company_type              6140
last_new_job               423
training_hours               0
target                       0
dtype: int64

this will help us to determine where we have to fill values and which columns we should remove

## How does the data look mathematically?

In [12]:
df.describe()

        enrollee_id  city_development_index  training_hours        target
count  19158.000000            19158.000000    19158.000000  19158.000000
mean   16875.358179                0.828848       65.366896      0.249348
std     9616.292592                0.123362       60.058462      0.432647
min        1.000000                0.448000        1.000000      0.000000
25%     8554.250000                0.740000       23.000000      0.000000
50%    16982.500000                0.903000       47.000000      0.000000
75%    25169.750000                0.920000       88.000000      0.000000
max    33380.000000                0.949000      336.000000      1.000000

mathematical insights of only columns with numerical values

## Are there duplicate values?

In [13]:
df.duplicated().sum()

np.int64(0)

we can drop duplicate values using drop duplicate function.

## How is the correlation between cols?

In [15]:
df.corr(numeric_only=True)

,enrollee_id,city_development_index,training_hours,target
enrollee_id,1.000000,-0.040455,0.000998,0.049475
city_development_index,-0.040455,1.000000,0.001920,-0.341665
training_hours,0.000998,0.001920,1.000000,-0.021577
target,0.049475,-0.341665,-0.021577,1.000000

In [19]:
df.corr(numeric_only=True)["training_hours"]

enrollee_id               0.000998
city_development_index    0.001920
training_hours            1.000000
target                   -0.021577
Name: training_hours, dtype: float64